# Generated by Django 2.0.3 on 2018-04-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='entrée',
            name='cri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrée',
            name='photo1_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='entrée',
            name='photo2_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='entrée',
            name='photo3_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='entrée',
            name='sources',
            field=models.ManyToManyField(blank=True, to='animals.Source'),
        ),
    ]
