# Generated by Django 2.0.3 on 2018-04-01 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_latin', models.CharField(max_length=200)),
                ('nom_vernaculaire', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Espèce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_latin', models.CharField(max_length=200)),
                ('nom_vernaculaire', models.CharField(blank=True, max_length=200, null=True)),
                ('date_découverte', models.IntegerField(blank=True, null=True)),
                ('inpn_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_latin', models.CharField(max_length=200)),
                ('nom_vernaculaire', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_latin', models.CharField(max_length=200)),
                ('nom_vernaculaire', models.CharField(blank=True, max_length=200, null=True)),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.Famille')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Naturaliste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ordre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_latin', models.CharField(max_length=200)),
                ('nom_vernaculaire', models.CharField(blank=True, max_length=200, null=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.Classe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phylum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_latin', models.CharField(max_length=200)),
                ('nom_vernaculaire', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='famille',
            name='ordre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.Ordre'),
        ),
        migrations.AddField(
            model_name='espèce',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.Genre'),
        ),
        migrations.AddField(
            model_name='espèce',
            name='naturaliste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.Naturaliste'),
        ),
        migrations.AddField(
            model_name='classe',
            name='phylum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.Phylum'),
        ),
        migrations.AlterUniqueTogether(
            name='espèce',
            unique_together={('genre', 'nom_latin')},
        ),
    ]
